const categoryDescriptions = {
    "Electronics": "Stay updated with the latest in technology with our vast collection of electronics. Find everything from mobile phones, laptops, tablets, cameras, and televisions to audio & headphones, wearable technology, smart home devices, and gaming consoles. Embrace innovation and enhance your digital life with our high-quality gadgets.",
    "Fashion": "Step into style with our diverse range of fashion items. Shop for men's, women's, and kid's clothing, including trendy footwear and a variety of accessories like bags, belts, hats, and jewelry. Whether you're dressing up for an occasion or looking for everyday wear, we have something for everyone.",
    "Home & Living": "Transform your living space with our exquisite Home & Living collection. Discover furniture, home décor, bedding & bath essentials, kitchen appliances, lighting, and storage & organization solutions. Create a cozy and stylish home that reflects your personal taste.",
    "Beauty & Health": "Enhance your beauty and well-being with our selection of Beauty & Health products. Explore skincare, makeup, hair care, personal care items, health supplements, and fitness equipment. Stay healthy, look great, and feel your best with our premium products.",
    "Books & Media": "Immerse yourself in our extensive Books & Media collection. Find fiction and non-fiction books, e-books, magazines, music, movies, and TV shows. Whether you're looking for the latest bestseller or a classic film, our diverse selection has something to entertain and inspire everyone.",
    "Toys & Hobbies": "Unleash your creativity and have fun with our Toys & Hobbies selection. Browse action figures, dolls & plushies, educational toys, board games, puzzles, and arts & crafts. Perfect for kids and adults alike, our toys and hobby items provide endless entertainment and learning opportunities.",
    "Sports & Outdoors": "Gear up for your next adventure with our Sports & Outdoors collection. Find sports equipment, outdoor gear, bicycles, camping equipment, and fitness & exercise essentials. Stay active and enjoy the great outdoors with our top-quality products.",
    "Automotive": "Keep your vehicle in top condition with our Automotive range. Discover car and motorcycle accessories, tools & equipment, and car electronics. Whether you're upgrading your car's tech or looking for maintenance tools, we have everything you need for your vehicle.",
    "Groceries & Food": "Satisfy your culinary cravings with our Groceries & Food selection. Shop for fresh produce, beverages, snacks, pantry staples, and gourmet & specialty foods. From everyday essentials to unique gourmet treats, find all your food and beverage needs here.",
    "Office Supplies": "Boost your productivity with our Office Supplies. Explore stationery, office furniture, printers & scanners, and office electronics. Create a functional and efficient workspace with our high-quality office essentials.",
    "Pets": "Pamper your pets with our comprehensive Pets collection. Find pet food, accessories, toys, and care products. Ensure your furry friends are happy, healthy, and well taken care of with our wide range of pet supplies.",
    "Baby & Kids": "Find everything you need for your little ones in our Baby & Kids collection. Shop for baby clothing, gear like strollers and car seats, nursery furniture, toys, and diapers & wipes. Discover safe and reliable products for your baby's needs.",
    "Gifts & Occasions": "Celebrate life's special moments with our Gifts & Occasions range. Browse flowers & bouquets, gift baskets, personalized gifts, and party supplies. Find the perfect gift or decor for any occasion and make your celebrations memorable.",
    "Crafts & Sewing": "Unleash your creativity with our Crafts & Sewing supplies. Explore fabric & sewing supplies, craft materials, and art supplies. Whether you're a DIY enthusiast or a professional crafter, find everything you need for your next project.",
    "Travel": "Prepare for your next journey with our Travel collection. Discover luggage & bags, travel accessories, and travel guides. From packing essentials to informative guides, we have everything to make your travel experience smooth and enjoyable.",
    "Specialty Shops": "Explore unique and niche products in our Specialty Shops. Find eco-friendly products, handmade items, and seasonal products like holiday decor. Discover one-of-a-kind items that stand out and cater to specific interests and occasions."
  };
  
  export default categoryDescriptions;
  
  